apiVersion: v1
kind: Service
metadata:
  name: vscode-service
  namespace: default
  labels:
    app: vscode-pod
spec:
  #type: NodePort
  type: LoadBalancer
  #loadBalancerIP: "34.73.160.140"
  ports:
  - port: 8443
    name: https
    protocol: TCP
    targetPort: 8443
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  - port: 8080
    name: app1
    protocol: TCP
    targetPort: 8080
  - port: 5000
    name: app2
    protocol: TCP
    targetPort: 5000
  - port: 3000
    name: app3
    protocol: TCP
    targetPort: 3000
  - port: 9090
    name: app4
    protocol: TCP
    targetPort: 9090
  selector:
    app: vscode-pod
