#version: "2"
#services:
web:
    build: . #utiliza Dockerfile
    volumes:
        - .:/platzi
    links:
        - redis # composer vincula solo el redist de primeras
    expose:
        - "5000"
#   ports:
#       - "80:5000"

redis:
    image: redis

lb:
    image: tutum/haproxy
    links:
        - web
    ports:
        - "80:80"
    environment:
        - BACKEND_PORT=5000
        - BALANCE=roundrobin

