web:
    image: marcosnils/python-redis
    links:
        - redis
    expose:
        - "5000"
redis:
    image: redis

lb:
    image: tutum/haproxy
    links:
        - web
    ports:
        - "8080:80"
    environment:
        - BACKEND_PORT=5000
        - BALANCE=roundrobin

